CREATE TABLE IF NOT EXISTS MATIC.BLOCK(
  `BLOCK_NUMBER` BIGINT NOT NULL,
  `TIME_STAMP` TIMESTAMP,
  `BLOCK_HASH` VARCHAR,
  `MINER` VARCHAR,
  `REWARD` DECIMAL(90, 0),
  `SIZE_` INT,
  `GAS_USED` INT,
  `GAS_LIMIT` INT,
  `BASE_FEE_PER_GAS` DECIMAL(90, 0),
  `TRANSACTION_COUNT` INT,
  `PARENT_HASH` VARCHAR,
  PRIMARY KEY(BLOCK_NUMBER)
) WITH "AFFINITY_KEY=BLOCK_NUMBER, TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=false,immutable=true,access_type=public_read";

CREATE TABLE IF NOT EXISTS MATIC.MULTIPASS_MULTIPASSMINTED (
  `TRANSACTION_HASH` VARCHAR NOT NULL,
  `EVENT_INDEX` INT NOT NULL,
  `OWNER` VARCHAR,
  `TOKENID` DECIMAL(78, 0),
  `BLOCK_NUMBER` LONG,
  `TIMESTAMP` TIMESTAMP,
  `CONTRACT_ADDRESS` VARCHAR,
  PRIMARY KEY(TRANSACTION_HASH, EVENT_INDEX),
  FOREIGN KEY (BLOCK_NUMBER) REFERENCES MATIC.BLOCK(BLOCK_NUMBER),
  FOREIGN KEY (TRANSACTION_HASH) REFERENCES MATIC.TRANSACTION(TRANSACTION_HASH)
) WITH "AFFINITY_KEY=TRANSACTION_HASH, TEMPLATE=SxTCacheTemplate";

